import { Mail, MessageCircle, ShieldCheck, GitBranch, Send, CheckSquare, Sparkles } from 'lucide-react';

export function Workflows(){return <Shell title="Workflow Control" subtitle="Approval routes, response SLAs, escalations and conditional steps." icon={<GitBranch size={18}/>}><p>Workflow definitions remain backed by the existing document workflow APIs. This screen is isolated from the legacy CRM navigation so the Figma workflow builder can be implemented incrementally without changing existing behavior.</p></Shell>}
export function Transmittals(){return <Shell title="Transmittals" subtitle="Controlled document issue, acknowledgement and response tracking." icon={<Send size={18}/>}><p>Use this area for formal document issue packages and receipt status. The next backend slice will persist transmittal headers/items against project documents rather than treating WhatsApp messages as the official record.</p></Shell>}
export function Approvals(){return <Shell title="Approval Inbox" subtitle="My document and IPC actions, sorted by contractual urgency." icon={<CheckSquare size={18}/>}><p>Document approval and IPC certification authorization already lives in the backend. This surface will consolidate those queues without bypassing the existing server-side permission checks.</p></Shell>}
export function Insights(){return <Shell title="AI Insights" subtitle="Grounded suggestions and predictions from project records." icon={<Sparkles size={18}/>}><p>The overview now calls a dedicated grounded commercial AI endpoint. AI receives server-calculated IPC, budget and SLA metrics only; it cannot certify work, approve a document or release payment.</p></Shell>}
export function Audit(){return <Shell title="Audit & Compliance" subtitle="Evidence chain for document, approval and payment decisions." icon={<ShieldCheck size={18}/>}><p>Existing document and payment audit chains remain the source of truth. The enterprise UI will surface these histories without introducing a second audit store.</p></Shell>}

export function Communications(){return <div className="ec-page"><header className="ec-topbar"><div className="ec-title"><h1>WhatsApp & Email</h1><p>Use communication channels for reminders and responses; keep controlled documents and approvals in the system of record.</p></div></header><div className="ec-channel-grid">
 <div className="ec-card ec-channel"><div className="ec-channel-icon"><MessageCircle size={20}/></div><div><h3>WhatsApp Bot</h3><p>Existing Graph API sender, webhook processing, interactive replies and tenant AI remain available. Document/IPC reminders can use these capabilities without moving authorization decisions into WhatsApp.</p><span className="ec-badge green" style={{marginTop:10}}>Backend available</span></div></div>
 <div className="ec-card ec-channel"><div className="ec-channel-icon"><Mail size={20}/></div><div><h3>Email responses</h3><p>The current Spring Boot project does not contain an outbound email adapter. The UI intentionally does not claim that email is active until SMTP, Microsoft 365 or a transactional-email provider is configured.</p><span className="ec-badge amber" style={{marginTop:10}}>Adapter required</span></div></div>
 </div><div className="ec-card ec-section"><div className="ec-card-title"><h2>Channel policy</h2><span>Enterprise control</span></div><div className="ec-insight"><div className="ec-insight-dot"/><div>WhatsApp/email can notify, collect comments and link users back to an action.</div></div><div className="ec-insight"><div className="ec-insight-dot"/><div>Document approval, IPC certification and payment release must remain authenticated actions in the application.</div></div><div className="ec-insight"><div className="ec-insight-dot"/><div>Every channel message should carry project/document/IPC correlation identifiers for auditability.</div></div></div></div>}

function Shell({title,subtitle,icon,children}:{title:string;subtitle:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="ec-page"><header className="ec-topbar"><div className="ec-title"><h1>{title}</h1><p>{subtitle}</p></div></header><div className="ec-card"><div className="ec-card-title"><h2>{icon} <span style={{verticalAlign:'top',color:'#102a43',fontSize:14}}>{title}</span></h2><span>Enterprise module</span></div><div style={{fontSize:12,color:'#6b7c93',lineHeight:1.7}}>{children}</div></div></div>}
