import { useEffect, useMemo, useState } from 'react';
import { enterpriseApi, type CapabilityOverride, type DocumentRecord, type PermissionAudit, type Project, type ProjectParticipant } from './enterpriseApi';

const permissions=['DOCUMENT_VIEW','DOCUMENT_CREATE','DOCUMENT_EDIT','DOCUMENT_ISSUE','DOCUMENT_REVIEW_INTERNAL','DOCUMENT_REVIEW_TECHNICAL','DOCUMENT_APPROVE_CLIENT','DOCUMENT_CERTIFY_COMMERCIAL','TRANSMITTAL_VIEW','TRANSMITTAL_CREATE','TRANSMITTAL_ISSUE','TRANSMITTAL_ACKNOWLEDGE','COMMERCIAL_VIEW_PROJECT','COMMERCIAL_VIEW_ORGANIZATION','BUDGET_EDIT_PROJECT','FORECAST_SUBMIT_ORGANIZATION','PAYMENT_VIEW_PROJECT','PAYMENT_VIEW_ORGANIZATION','PAYMENT_CREATE_ORGANIZATION','PAYMENT_CERTIFY','PAYMENT_MARK_PAID'];
export default function SecurityAccess(){
  const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[docs,setDocs]=useState<DocumentRecord[]>([]),[participants,setParticipants]=useState<ProjectParticipant[]>([]);
  const [overrides,setOverrides]=useState<CapabilityOverride[]>([]),[audit,setAudit]=useState<PermissionAudit[]>([]);
  const [documentId,setDocumentId]=useState(''),[classification,setClassification]=useState('PROJECT'),[organizationId,setOrganizationId]=useState('');
  const [partyRole,setPartyRole]=useState('CONTRACTOR'),[userRole,setUserRole]=useState('MANAGER'),[permission,setPermission]=useState('DOCUMENT_VIEW'),[effect,setEffect]=useState<'ALLOW'|'DENY'>('ALLOW'),[scope,setScope]=useState<'PROJECT'|'ORGANIZATION'|'ASSIGNED'>('ORGANIZATION');
  const [error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{Promise.all([enterpriseApi.projects(),enterpriseApi.documents()]).then(([p,d])=>{setProjects(p);setDocs(d);if(p.length)setProjectId(p[0].id)}).catch(e=>setError(String(e)))},[]);
  const loadProject=async(id:string)=>{if(!id)return;const [p,o,a]=await Promise.all([enterpriseApi.participants(id),enterpriseApi.capabilityOverrides(id),enterpriseApi.permissionAudit(id)]);setParticipants(p);setOverrides(o);setAudit(a)};
  useEffect(()=>{void loadProject(projectId).catch(e=>setError(String(e)))},[projectId]);
  const projectDocs=useMemo(()=>docs.filter(d=>d.projectId===projectId),[docs,projectId]);
  const selected=projectDocs.find(d=>d.id===documentId);
  const selectDocument=(id:string)=>{setDocumentId(id);const d=projectDocs.find(x=>x.id===id);setClassification(d?.securityClassification||'PROJECT')};
  const run=async(fn:()=>Promise<unknown>,ok:string)=>{setError('');setMessage('');try{await fn();setMessage(ok);await loadProject(projectId)}catch(e){setError(String(e))}};
  const save=()=>documentId?run(()=>enterpriseApi.setDocumentSecurity(documentId,{classification,discipline:selected?.discipline,packageCode:selected?.packageCode,locationCode:selected?.locationCode}),'Security classification updated.'):undefined;
  const grant=()=>documentId&&organizationId?run(()=>enterpriseApi.grantDocument(documentId,{organizationId,permission:'VIEW'}),'Organization VIEW grant added.'):undefined;
  const setCapability=()=>run(()=>enterpriseApi.setCapabilityOverride(projectId,{partyRole,userRole,permissionCode:permission,effect,dataScope:effect==='ALLOW'?scope:undefined}),'Capability override saved.');
  const reset=(x:CapabilityOverride)=>run(()=>enterpriseApi.resetCapabilityOverride(projectId,x.partyRole,x.userRole,x.permissionCode),'Override reset to platform default.');
  return <div className="ec-page"><header className="ec-topbar"><div className="ec-title"><h1>Security & Access</h1><p>Project capability matrix, document grants/classification and immutable permission administration history.</p></div><select className="ec-select" value={projectId} onChange={e=>{setProjectId(e.target.value);setDocumentId('')}}>{projects.map(p=><option key={p.id} value={p.id}>{p.projectCode} — {p.name}</option>)}</select></header>{error&&<div className="ec-error">{error}</div>}{message&&<div className="ec-card" style={{marginBottom:12}}>{message}</div>}
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>Project role / capability matrix</h2><span>Tenant-admin overrides</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1.7fr .8fr 1fr auto',gap:8}}><select className="ec-select" value={partyRole} onChange={e=>setPartyRole(e.target.value)}><option>CLIENT</option><option>CONSULTANT</option><option>CONTRACTOR</option><option>SUBCONTRACTOR</option></select><select className="ec-select" value={userRole} onChange={e=>setUserRole(e.target.value)}><option>ADMIN</option><option>MANAGER</option><option>REVIEWER</option><option>VIEWER</option></select><select className="ec-select" value={permission} onChange={e=>setPermission(e.target.value)}>{permissions.map(x=><option key={x}>{x}</option>)}</select><select className="ec-select" value={effect} onChange={e=>setEffect(e.target.value as 'ALLOW'|'DENY')}><option>ALLOW</option><option>DENY</option></select><select className="ec-select" value={scope} disabled={effect==='DENY'} onChange={e=>setScope(e.target.value as typeof scope)}><option>ASSIGNED</option><option>ORGANIZATION</option><option>PROJECT</option></select><button className="ec-button" onClick={()=>void setCapability()}>Save</button></div><div className="ec-table-wrap" style={{marginTop:12}}><table className="ec-table"><thead><tr><th>Party</th><th>User role</th><th>Permission</th><th>Effect</th><th>Scope</th><th/></tr></thead><tbody>{overrides.map(x=><tr key={x.id}><td>{x.partyRole}</td><td>{x.userRole}</td><td>{x.permissionCode}</td><td><span className={`ec-badge ${x.effect==='ALLOW'?'green':'red'}`}>{x.effect}</span></td><td>{x.dataScope||'—'}</td><td><button className="ec-button" onClick={()=>void reset(x)}>Reset</button></td></tr>)}{!overrides.length&&<tr><td colSpan={6}><div className="ec-empty">No project overrides. Safe platform defaults are active.</div></td></tr>}</tbody></table></div></section>
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>Document classification</h2><span>Backend authoritative</span></div><div style={{display:'grid',gridTemplateColumns:'2fr 1fr auto',gap:10}}><select className="ec-select" value={documentId} onChange={e=>selectDocument(e.target.value)}><option value="">Select document…</option>{projectDocs.map(d=><option key={d.id} value={d.id}>{d.documentCode||d.title} — {d.title}</option>)}</select><select className="ec-select" value={classification} onChange={e=>setClassification(e.target.value)}><option>PROJECT</option><option>ORGANIZATION</option><option>RESTRICTED</option></select><button className="ec-button" disabled={!documentId} onClick={()=>void save()}>Apply</button></div></section>
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>Document company grant</h2><span>VIEW only</span></div><div style={{display:'grid',gridTemplateColumns:'2fr auto',gap:10}}><select className="ec-select" value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">Select active project company…</option>{participants.map(p=><option key={p.id} value={p.organizationId}>{p.organizationName} ({p.partyRole})</option>)}</select><button className="ec-button" disabled={!documentId||!organizationId} onClick={()=>void grant()}>Grant VIEW</button></div></section>
    <section className="ec-section"><div className="ec-card-title"><h2>Permission audit</h2><span>{audit.length} recent changes</span></div><div className="ec-table-wrap"><table className="ec-table"><thead><tr><th>Time</th><th>Actor</th><th>Event</th><th>Principal</th><th>Permission</th><th>Document</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString()}</td><td>{x.actorEmail||'System'}</td><td>{x.eventType}</td><td>{x.principalValue||'—'}</td><td>{x.permissionCode||'—'}</td><td>{x.documentId||'—'}</td></tr>)}{!audit.length&&<tr><td colSpan={6}><div className="ec-empty">No permission administration changes recorded for this project.</div></td></tr>}</tbody></table></div></section>
  </div>;
}
