import { useEffect, useMemo, useState } from 'react';
import { enterpriseApi, type DocumentRecord, type Project, type ProjectParticipant } from './enterpriseApi';

export default function SecurityAccess(){
  const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[docs,setDocs]=useState<DocumentRecord[]>([]),[participants,setParticipants]=useState<ProjectParticipant[]>([]);
  const [documentId,setDocumentId]=useState(''),[classification,setClassification]=useState('PROJECT'),[organizationId,setOrganizationId]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{Promise.all([enterpriseApi.projects(),enterpriseApi.documents()]).then(([p,d])=>{setProjects(p);setDocs(d);if(p.length)setProjectId(p[0].id)}).catch(e=>setError(String(e)))},[]);
  useEffect(()=>{if(projectId)enterpriseApi.participants(projectId).then(setParticipants).catch(e=>setError(String(e)))},[projectId]);
  const projectDocs=useMemo(()=>docs.filter(d=>d.projectId===projectId),[docs,projectId]);
  const selected=projectDocs.find(d=>d.id===documentId);
  const selectDocument=(id:string)=>{setDocumentId(id);const d=projectDocs.find(x=>x.id===id);setClassification(d?.securityClassification||'PROJECT')};
  const save=async()=>{if(!documentId)return;setError('');setMessage('');try{await enterpriseApi.setDocumentSecurity(documentId,{classification,discipline:selected?.discipline,packageCode:selected?.packageCode,locationCode:selected?.locationCode});setMessage('Security classification updated.')}catch(e){setError(String(e))}};
  const grant=async()=>{if(!documentId||!organizationId)return;setError('');setMessage('');try{await enterpriseApi.grantDocument(documentId,{organizationId,permission:'VIEW'});setMessage('Organization VIEW grant added.')}catch(e){setError(String(e))}};
  return <div className="ec-page"><header className="ec-topbar"><div className="ec-title"><h1>Security & Access</h1><p>Administer document classification and explicit company visibility without widening project commercial scope.</p></div></header>{error&&<div className="ec-error">{error}</div>}{message&&<div className="ec-card" style={{marginBottom:12}}>{message}</div>}
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>Document policy</h2><span>Backend authoritative</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 2fr 1fr auto',gap:10}}><select className="ec-select" value={projectId} onChange={e=>{setProjectId(e.target.value);setDocumentId('')}}>{projects.map(p=><option key={p.id} value={p.id}>{p.projectCode} — {p.name}</option>)}</select><select className="ec-select" value={documentId} onChange={e=>selectDocument(e.target.value)}><option value="">Select document…</option>{projectDocs.map(d=><option key={d.id} value={d.id}>{d.documentCode||d.title} — {d.title}</option>)}</select><select className="ec-select" value={classification} onChange={e=>setClassification(e.target.value)}><option>PROJECT</option><option>ORGANIZATION</option><option>RESTRICTED</option></select><button className="ec-button" disabled={!documentId} onClick={()=>void save()}>Apply</button></div></section>
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>Grant company visibility</h2><span>VIEW only</span></div><div style={{display:'grid',gridTemplateColumns:'2fr auto',gap:10}}><select className="ec-select" value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">Select active project company…</option>{participants.map(p=><option key={p.id} value={p.organizationId}>{p.organizationName} ({p.partyRole})</option>)}</select><button className="ec-button" disabled={!documentId||!organizationId} onClick={()=>void grant()}>Grant VIEW</button></div><div className="ec-kpi-meta" style={{marginTop:10}}>Company/role grants cannot grant EDIT or ISSUE. Cross-company mutation requires a named-user grant and still passes server-side project/document policy.</div></section>
  </div>;
}
