import { useEffect, useMemo, useRef, useState } from 'react';
import { enterpriseApi, type IssuedRevision, type Project, type ProjectParticipant, type Transmittal, type TransmittalDetail } from './enterpriseApi';

const badge=(s:string)=>s==='ACKNOWLEDGED'?'green':s==='ISSUED'||s==='PARTIALLY_ACKNOWLEDGED'?'amber':'teal';
export default function Transmittals(){
  const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState('');
  const [items,setItems]=useState<Transmittal[]>([]),[revisions,setRevisions]=useState<IssuedRevision[]>([]),[participants,setParticipants]=useState<ProjectParticipant[]>([]);
  const [activeDraft,setActiveDraft]=useState(''),[selectedRevision,setSelectedRevision]=useState(''),[selectedRecipient,setSelectedRecipient]=useState(''),[detail,setDetail]=useState<TransmittalDetail|null>(null);
  const [number,setNumber]=useState(''),[purpose,setPurpose]=useState('FOR_INFORMATION'),[subject,setSubject]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const latestProjectRef=useRef('');
  const reload=async(id:string)=>{if(!id)return;latestProjectRef.current=id;const [t,r,p]=await Promise.all([enterpriseApi.transmittals(id),enterpriseApi.issuedRevisions(id),enterpriseApi.participants(id)]);if(latestProjectRef.current!==id)return;setItems(t);setRevisions(r);setParticipants(p)};
  useEffect(()=>{enterpriseApi.projects().then(p=>{setProjects(p);if(p.length){setProjectId(p[0].id);void reload(p[0].id).catch(e=>setError(String(e)))}}).catch(e=>setError(String(e)))},[]);
  const selectProject=(id:string)=>{setProjectId(id);setActiveDraft('');setDetail(null);void reload(id).catch(e=>setError(String(e)))};
  const draft=items.find(x=>x.id===activeDraft);
  const counts=useMemo(()=>({draft:items.filter(x=>x.status==='DRAFT').length,open:items.filter(x=>x.status==='ISSUED'||x.status==='PARTIALLY_ACKNOWLEDGED').length,ack:items.filter(x=>x.status==='ACKNOWLEDGED').length}),[items]);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await reload(projectId);if(detail) setDetail(await enterpriseApi.transmittalDetail(detail.header.id))}catch(e){setError(String(e))}finally{setBusy(false)}};
  const create=()=>act(async()=>{const x=await enterpriseApi.createTransmittal(projectId,{transmittalNo:number.trim(),purpose,subject:subject.trim()||undefined});setActiveDraft(x.id);setNumber('');setSubject('')});
  const addRevision=()=>{const r=revisions.find(x=>x.versionId===selectedRevision);if(!draft||!r)return;return act(()=>enterpriseApi.addTransmittalItem(draft.id,r.documentId,r.versionId))};
  const addRecipient=()=>draft&&selectedRecipient?act(()=>enterpriseApi.addTransmittalRecipient(draft.id,selectedRecipient)):undefined;
  const openDetail=async(id:string)=>{setError('');try{setDetail(await enterpriseApi.transmittalDetail(id))}catch(e){setError(String(e))}};

  return <div className="ec-page"><header className="ec-topbar"><div className="ec-title"><h1>Transmittals</h1><p>Compose, issue, acknowledge and trace formal packages against exact issued revisions.</p></div><select className="ec-select" value={projectId} onChange={e=>selectProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.projectCode} — {p.name}</option>)}</select></header>{error&&<div className="ec-error">{error}</div>}
    <section className="ec-grid ec-three"><div className="ec-card"><div className="ec-kpi-label">Draft</div><div className="ec-kpi-value">{counts.draft}</div></div><div className="ec-card"><div className="ec-kpi-label">Awaiting acknowledgement</div><div className="ec-kpi-value">{counts.open}</div></div><div className="ec-card"><div className="ec-kpi-label">Acknowledged</div><div className="ec-kpi-value">{counts.ack}</div></div></section>
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>1. Create draft</h2><span>Sender derived server-side</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 2fr auto',gap:10}}><input className="ec-input" value={number} onChange={e=>setNumber(e.target.value)} placeholder="TR-0001"/><select className="ec-select" value={purpose} onChange={e=>setPurpose(e.target.value)}><option>FOR_INFORMATION</option><option>FOR_REVIEW</option><option>FOR_APPROVAL</option><option>FOR_CONSTRUCTION</option><option>AS_BUILT</option></select><input className="ec-input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><button className="ec-button" disabled={busy||!number.trim()} onClick={()=>void create()}>Create</button></div></section>
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>2. Compose draft</h2><span>Exact revision + recipient company</span></div><select className="ec-select" value={activeDraft} onChange={e=>setActiveDraft(e.target.value)}><option value="">Select draft…</option>{items.filter(x=>x.status==='DRAFT').map(x=><option key={x.id} value={x.id}>{x.transmittalNo} — {x.subject||x.purpose}</option>)}</select>{draft&&<div style={{display:'grid',gridTemplateColumns:'2fr auto 2fr auto auto',gap:10,marginTop:12}}><select className="ec-select" value={selectedRevision} onChange={e=>setSelectedRevision(e.target.value)}><option value="">Issued revision…</option>{revisions.map(r=><option key={r.versionId} value={r.versionId}>{r.documentCode||r.title} — {r.revisionCode}</option>)}</select><button className="ec-button" disabled={busy||!selectedRevision} onClick={()=>void addRevision()}>Add revision</button><select className="ec-select" value={selectedRecipient} onChange={e=>setSelectedRecipient(e.target.value)}><option value="">Recipient company…</option>{participants.map(p=><option key={p.id} value={p.organizationId}>{p.organizationName} ({p.partyRole})</option>)}</select><button className="ec-button" disabled={busy||!selectedRecipient} onClick={()=>void addRecipient()}>Add recipient</button><button className="ec-button" disabled={busy||draft.itemCount<1||draft.recipientCount<1} onClick={()=>void act(()=>enterpriseApi.issueTransmittal(draft.id))}>Issue</button></div>}</section>
    <section className="ec-section"><div className="ec-card-title"><h2>Register</h2><span>{items.length} visible in your company scope</span></div><div className="ec-table-wrap"><table className="ec-table"><thead><tr><th>No.</th><th>Sender</th><th>Purpose</th><th>Subject</th><th>Docs</th><th>Recipients</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td><button className="ec-button" onClick={()=>void openDetail(t.id)}>{t.transmittalNo}</button></td><td>{t.senderOrganizationName}</td><td>{t.purpose}</td><td>{t.subject||'—'}</td><td>{t.itemCount}</td><td>{t.recipientCount}</td><td><span className={`ec-badge ${badge(t.status)}`}>{t.status}</span></td><td>{(t.status==='ISSUED'||t.status==='PARTIALLY_ACKNOWLEDGED')?<button className="ec-button" disabled={busy} onClick={()=>void act(()=>enterpriseApi.acknowledgeTransmittal(t.id))}>Acknowledge</button>:'—'}</td></tr>)}</tbody></table></div></section>
    {detail&&<section className="ec-card ec-section"><div className="ec-card-title"><h2>{detail.header.transmittalNo} detail</h2><span>{detail.header.status}</span></div><div className="ec-grid ec-three"><div><strong>Sender</strong><div>{detail.header.senderOrganizationName}</div></div><div><strong>Purpose</strong><div>{detail.header.purpose}</div></div><div><strong>Issued</strong><div>{detail.header.issuedAt?new Date(detail.header.issuedAt).toLocaleString():'Draft'}</div></div></div><h3 style={{marginTop:18}}>Issued revisions</h3><div className="ec-table-wrap"><table className="ec-table"><thead><tr><th>Document</th><th>Revision</th><th>Purpose</th></tr></thead><tbody>{detail.items.map(x=><tr key={x.id}><td>{x.documentCode||x.title} — {x.title}</td><td>{x.revisionCode}</td><td>{x.issuePurpose||'—'}</td></tr>)}</tbody></table></div><h3 style={{marginTop:18}}>Recipients</h3><div className="ec-table-wrap"><table className="ec-table"><thead><tr><th>Organization</th><th>Acknowledged</th><th>By</th></tr></thead><tbody>{detail.recipients.map(x=><tr key={x.id}><td>{x.organizationName}</td><td>{x.acknowledgedAt?new Date(x.acknowledgedAt).toLocaleString():'Pending'}</td><td>{x.acknowledgedByEmail||'—'}</td></tr>)}</tbody></table></div><h3 style={{marginTop:18}}>History</h3>{detail.history.map((h,i)=><div key={`${h.eventType}-${i}`} className="ec-insight"><div className="ec-insight-dot"/><div><strong>{h.eventType.replaceAll('_',' ')}</strong> — {new Date(h.at).toLocaleString()} · {h.subject||''} {h.detail?`· ${h.detail}`:''}</div></div>)}</section>}
  </div>;
}
