import { useEffect, useMemo, useState } from 'react';
import { enterpriseApi, type IssuedRevision, type Project, type ProjectParticipant, type Transmittal } from './enterpriseApi';

const badge=(s:string)=>s==='ACKNOWLEDGED'?'green':s==='ISSUED'||s==='PARTIALLY_ACKNOWLEDGED'?'amber':'teal';

export default function Transmittals(){
  const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState('');
  const [items,setItems]=useState<Transmittal[]>([]),[revisions,setRevisions]=useState<IssuedRevision[]>([]),[participants,setParticipants]=useState<ProjectParticipant[]>([]);
  const [activeDraft,setActiveDraft]=useState(''),[selectedRevision,setSelectedRevision]=useState(''),[selectedRecipient,setSelectedRecipient]=useState('');
  const [number,setNumber]=useState(''),[purpose,setPurpose]=useState('FOR_INFORMATION'),[subject,setSubject]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const reload=async(id=projectId)=>{if(!id)return;const [t,r,p]=await Promise.all([enterpriseApi.transmittals(id),enterpriseApi.issuedRevisions(id),enterpriseApi.participants(id)]);setItems(t);setRevisions(r);setParticipants(p);};
  useEffect(()=>{enterpriseApi.projects().then(p=>{setProjects(p);if(p.length)setProjectId(p[0].id)}).catch(e=>setError(String(e)))},[]);
  useEffect(()=>{reload().catch(e=>setError(String(e)))},[projectId]);
  const draft=items.find(x=>x.id===activeDraft);
  const counts=useMemo(()=>({draft:items.filter(x=>x.status==='DRAFT').length,open:items.filter(x=>x.status==='ISSUED'||x.status==='PARTIALLY_ACKNOWLEDGED').length,ack:items.filter(x=>x.status==='ACKNOWLEDGED').length}),[items]);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await reload()}catch(e){setError(String(e))}finally{setBusy(false)}};
  const create=()=>act(async()=>{const x=await enterpriseApi.createTransmittal(projectId,{transmittalNo:number.trim(),purpose,subject:subject.trim()||undefined});setActiveDraft(x.id);setNumber('');setSubject('')});
  const addRevision=()=>{const r=revisions.find(x=>x.versionId===selectedRevision);if(!draft||!r)return;return act(()=>enterpriseApi.addTransmittalItem(draft.id,r.documentId,r.versionId))};
  const addRecipient=()=>draft&&selectedRecipient?act(()=>enterpriseApi.addTransmittalRecipient(draft.id,selectedRecipient)):undefined;

  return <div className="ec-page">
    <header className="ec-topbar"><div className="ec-title"><h1>Transmittals</h1><p>Compose, issue and acknowledge formal packages against exact issued revisions.</p></div><select className="ec-select" value={projectId} onChange={e=>{setProjectId(e.target.value);setActiveDraft('')}}>{projects.map(p=><option key={p.id} value={p.id}>{p.projectCode} — {p.name}</option>)}</select></header>
    {error&&<div className="ec-error">{error}</div>}
    <section className="ec-grid ec-three"><div className="ec-card"><div className="ec-kpi-label">Draft</div><div className="ec-kpi-value">{counts.draft}</div></div><div className="ec-card"><div className="ec-kpi-label">Awaiting acknowledgement</div><div className="ec-kpi-value">{counts.open}</div></div><div className="ec-card"><div className="ec-kpi-label">Acknowledged</div><div className="ec-kpi-value">{counts.ack}</div></div></section>

    <section className="ec-card ec-section"><div className="ec-card-title"><h2>1. Create draft</h2><span>Sender is derived server-side</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 2fr auto',gap:10}}><input className="ec-input" value={number} onChange={e=>setNumber(e.target.value)} placeholder="TR-0001"/><select className="ec-select" value={purpose} onChange={e=>setPurpose(e.target.value)}><option>FOR_INFORMATION</option><option>FOR_REVIEW</option><option>FOR_APPROVAL</option><option>FOR_CONSTRUCTION</option><option>AS_BUILT</option></select><input className="ec-input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><button className="ec-button" disabled={busy||!number.trim()} onClick={()=>void create()}>Create</button></div></section>

    <section className="ec-card ec-section"><div className="ec-card-title"><h2>2. Compose draft</h2><span>Exact revision + recipient company</span></div><select className="ec-select" value={activeDraft} onChange={e=>setActiveDraft(e.target.value)}><option value="">Select draft…</option>{items.filter(x=>x.status==='DRAFT').map(x=><option key={x.id} value={x.id}>{x.transmittalNo} — {x.subject||x.purpose}</option>)}</select>{draft&&<div style={{display:'grid',gridTemplateColumns:'2fr auto 2fr auto auto',gap:10,marginTop:12}}><select className="ec-select" value={selectedRevision} onChange={e=>setSelectedRevision(e.target.value)}><option value="">Issued revision…</option>{revisions.map(r=><option key={r.versionId} value={r.versionId}>{r.documentCode||r.title} — {r.revisionCode}</option>)}</select><button className="ec-button" disabled={busy||!selectedRevision} onClick={()=>void addRevision()}>Add revision</button><select className="ec-select" value={selectedRecipient} onChange={e=>setSelectedRecipient(e.target.value)}><option value="">Recipient company…</option>{participants.map(p=><option key={p.id} value={p.organizationId}>{p.organizationName} ({p.partyRole})</option>)}</select><button className="ec-button" disabled={busy||!selectedRecipient} onClick={()=>void addRecipient()}>Add recipient</button><button className="ec-button" disabled={busy||draft.itemCount<1||draft.recipientCount<1} onClick={()=>void act(()=>enterpriseApi.issueTransmittal(draft.id))}>Issue</button></div>}</section>

    <section className="ec-section"><div className="ec-card-title"><h2>Register</h2><span>{items.length} visible in your company scope</span></div><div className="ec-table-wrap"><table className="ec-table"><thead><tr><th>No.</th><th>Sender</th><th>Purpose</th><th>Subject</th><th>Docs</th><th>Recipients</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td className="ec-doc-code">{t.transmittalNo}</td><td>{t.senderOrganizationName}</td><td>{t.purpose}</td><td>{t.subject||'—'}</td><td>{t.itemCount}</td><td>{t.recipientCount}</td><td><span className={`ec-badge ${badge(t.status)}`}>{t.status}</span></td><td>{(t.status==='ISSUED'||t.status==='PARTIALLY_ACKNOWLEDGED')?<button className="ec-button" disabled={busy} onClick={()=>void act(()=>enterpriseApi.acknowledgeTransmittal(t.id))}>Acknowledge</button>:'—'}</td></tr>)}{!items.length&&<tr><td colSpan={8}><div className="ec-empty">No transmittals in your visible scope.</div></td></tr>}</tbody></table></div></section>
  </div>;
}
