import { useEffect, useState } from 'react';
import { enterpriseApi, type Workflow, type WorkflowStepDefinition } from './enterpriseApi';

const blank=():WorkflowStepDefinition=>({name:'',authority:'TECHNICAL_REVIEW',assignmentType:'PARTY_ROLE',partyRole:'CONSULTANT',required:true,slaHours:48});
export default function WorkflowControl(){
  const [workflows,setWorkflows]=useState<Workflow[]>([]),[name,setName]=useState(''),[docType,setDocType]=useState('GENERAL'),[steps,setSteps]=useState<WorkflowStepDefinition[]>([blank()]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const load=()=>enterpriseApi.workflows().then(setWorkflows).catch(e=>setError(String(e)));
  useEffect(()=>{load()},[]);
  const update=(i:number,key:keyof WorkflowStepDefinition,value:string|boolean|number)=>setSteps(v=>v.map((s,n)=>n===i?{...s,[key]:value}:s));
  const add=()=>setSteps(v=>[...v,blank()]);
  const save=async()=>{setBusy(true);setError('');try{await enterpriseApi.createWorkflow({name,docType,steps:JSON.stringify(steps)});setName('');setSteps([blank()]);await load()}catch(e){setError(String(e))}finally{setBusy(false)}};
  return <div className="ec-page"><header className="ec-topbar"><div className="ec-title"><h1>Workflow Control</h1><p>Configure who reviews, who approves, and the SLA for every contractual stage.</p></div></header>{error&&<div className="ec-error">{error}</div>}
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>New template</h2><span>Tenant-admin controlled</span></div><div style={{display:'grid',gridTemplateColumns:'2fr 1fr auto',gap:10}}><input className="ec-input" value={name} onChange={e=>setName(e.target.value)} placeholder="Shop Drawing Approval"/><input className="ec-input" value={docType} onChange={e=>setDocType(e.target.value.toUpperCase())} placeholder="SHOP_DRAWING"/><button className="ec-button" onClick={add}>Add stage</button></div>
      {steps.map((s,i)=><div key={i} className="ec-filterbar" style={{marginTop:10,display:'grid',gridTemplateColumns:'1.5fr 1.3fr 1fr 1fr .8fr auto',gap:8}}><input className="ec-input" value={s.name} onChange={e=>update(i,'name',e.target.value)} placeholder={`Stage ${i+1}`}/><select className="ec-select" value={s.authority} onChange={e=>update(i,'authority',e.target.value)}><option>INTERNAL_REVIEW</option><option>TECHNICAL_REVIEW</option><option>CLIENT_APPROVAL</option><option>COMMERCIAL_CERTIFICATION</option></select><select className="ec-select" value={s.assignmentType} onChange={e=>update(i,'assignmentType',e.target.value)}><option>PARTY_ROLE</option><option>USER</option><option>ORGANIZATION</option></select>{s.assignmentType==='PARTY_ROLE'?<select className="ec-select" value={s.partyRole||''} onChange={e=>update(i,'partyRole',e.target.value)}><option>CLIENT</option><option>CONSULTANT</option><option>CONTRACTOR</option><option>SUBCONTRACTOR</option></select>:s.assignmentType==='USER'?<input className="ec-input" value={s.reviewerEmail||''} onChange={e=>update(i,'reviewerEmail',e.target.value)} placeholder="reviewer@company.com"/>:<input className="ec-input" value={s.organizationId||''} onChange={e=>update(i,'organizationId',e.target.value)} placeholder="Organization UUID"/>}<input className="ec-input" type="number" min={1} value={s.slaHours||''} onChange={e=>update(i,'slaHours',Number(e.target.value))} placeholder="SLA hrs"/><button className="ec-button" disabled={steps.length===1} onClick={()=>setSteps(v=>v.filter((_,n)=>n!==i))}>Remove</button></div>)}
      <button className="ec-button" disabled={busy||!name.trim()||!docType.trim()} onClick={()=>void save()} style={{marginTop:12}}>{busy?'Saving…':'Save workflow'}</button>
    </section>
    <section className="ec-section"><div className="ec-card-title"><h2>Templates</h2><span>{workflows.length}</span></div><div className="ec-table-wrap"><table className="ec-table"><thead><tr><th>Name</th><th>Document type</th><th>Stages</th><th>Status</th></tr></thead><tbody>{workflows.map(w=>{let count=0;try{count=JSON.parse(w.steps).length}catch{count=0}return <tr key={w.id}><td>{w.name}</td><td>{w.docType}</td><td>{count}</td><td><span className={`ec-badge ${w.active?'green':'amber'}`}>{w.active?'ACTIVE':'INACTIVE'}</span></td></tr>})}</tbody></table></div></section>
  </div>;
}
