import { useEffect, useState } from 'react';
import { enterpriseApi, type Organization, type Workflow, type WorkflowStepDefinition } from './enterpriseApi';

const blank=():WorkflowStepDefinition=>({name:'',authority:'TECHNICAL_REVIEW',assignmentType:'PARTY_ROLE',partyRole:'CONSULTANT',required:true,slaHours:48});
const stageCount=(json:string)=>{try{return (JSON.parse(json) as unknown[]).length}catch{return 0}};
export default function WorkflowControl(){
  const [workflows,setWorkflows]=useState<Workflow[]>([]),[name,setName]=useState(''),[docType,setDocType]=useState('GENERAL'),[steps,setSteps]=useState<WorkflowStepDefinition[]>([blank()]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [organizations,setOrganizations]=useState<Organization[]>([]);
  const load=()=>enterpriseApi.workflows().then(setWorkflows).catch(e=>setError(String(e)));
  useEffect(()=>{enterpriseApi.workflows().then(setWorkflows).catch(e=>setError(String(e)))},[]);
  // The server rejects a company that is not active in this tenant, so the field is a picker
  // rather than a UUID box the user has to source from somewhere else.
  useEffect(()=>{enterpriseApi.organizations().then(setOrganizations).catch(e=>setError(String(e)))},[]);
  const update=(i:number,key:keyof WorkflowStepDefinition,value:string|boolean|number)=>setSteps(v=>v.map((s,n)=>n===i?{...s,[key]:value}:s));
  const add=()=>setSteps(v=>[...v,blank()]);
  const save=async()=>{setBusy(true);setError('');try{await enterpriseApi.createWorkflow({name,docType,steps:JSON.stringify(steps)});setName('');setSteps([blank()]);await load()}catch(e){setError(String(e))}finally{setBusy(false)}};
  return <div className="ec-page"><header className="ec-topbar"><div className="ec-title"><h1>Workflow Control</h1><p>Sequential and true parallel contractual stages with explicit authority, assignment and SLA.</p></div></header>{error&&<div className="ec-error">{error}</div>}
    <section className="ec-card ec-section"><div className="ec-card-title"><h2>New template</h2><span>Tenant-admin controlled</span></div><div style={{display:'grid',gridTemplateColumns:'2fr 1fr auto',gap:10}}><input className="ec-input" value={name} onChange={e=>setName(e.target.value)} placeholder="Shop Drawing Approval"/><input className="ec-input" value={docType} onChange={e=>setDocType(e.target.value.toUpperCase())} placeholder="SHOP_DRAWING"/><button className="ec-button" onClick={add}>Add reviewer</button></div>
      {steps.map((s,i)=><div key={i} className="ec-filterbar" style={{marginTop:10,display:'grid',gridTemplateColumns:'1.4fr 1.25fr 1fr 1.15fr .8fr .9fr .65fr auto',gap:8,alignItems:'center'}}><input className="ec-input" value={s.name} onChange={e=>update(i,'name',e.target.value)} placeholder={`Stage ${i+1}`}/><select className="ec-select" value={s.authority} onChange={e=>update(i,'authority',e.target.value)}><option>INTERNAL_REVIEW</option><option>TECHNICAL_REVIEW</option><option>CLIENT_APPROVAL</option><option>COMMERCIAL_CERTIFICATION</option></select><select className="ec-select" value={s.assignmentType} onChange={e=>update(i,'assignmentType',e.target.value)}><option>PARTY_ROLE</option><option>USER</option><option>ORGANIZATION</option></select>{s.assignmentType==='PARTY_ROLE'?<select className="ec-select" value={s.partyRole||''} onChange={e=>update(i,'partyRole',e.target.value)}><option>CLIENT</option><option>CONSULTANT</option><option>CONTRACTOR</option><option>SUBCONTRACTOR</option></select>:s.assignmentType==='USER'?<input className="ec-input" value={s.reviewerEmail||''} onChange={e=>update(i,'reviewerEmail',e.target.value)} placeholder="reviewer@company.com"/>:<select className="ec-select" value={s.organizationId||''} onChange={e=>update(i,'organizationId',e.target.value)}><option value="">Select company…</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.orgCode} — {o.name}</option>)}</select>}<input className="ec-input" value={s.parallelGroup||''} onChange={e=>update(i,'parallelGroup',e.target.value)} placeholder="Parallel group"/><input className="ec-input" type="number" min={1} value={s.slaHours||''} onChange={e=>update(i,'slaHours',Number(e.target.value))} placeholder="SLA hrs"/><label style={{fontSize:12,display:'flex',gap:5,alignItems:'center'}}><input type="checkbox" checked={s.required!==false} onChange={e=>update(i,'required',e.target.checked)}/>Required</label><button className="ec-button" disabled={steps.length===1} onClick={()=>setSteps(v=>v.filter((_,n)=>n!==i))}>Remove</button></div>)}
      <div className="ec-kpi-meta" style={{marginTop:10}}>Authority decides which project party may act: internal review belongs to the contractor, technical review to the consultant, client approval to the client. <strong>SLA hours</strong> starts counting when the stage becomes actionable and drives the due-soon and overdue notifications. Rows with the same contiguous <strong>Parallel group</strong> run concurrently. All required reviewers must approve before progression; optional reviewers do not block the stage. Optional rows therefore require a parallel group.</div>
      <button className="ec-button" disabled={busy||!name.trim()||!docType.trim()} onClick={()=>void save()} style={{marginTop:12}}>{busy?'Saving…':'Save workflow'}</button>
    </section>
    <section className="ec-section"><div className="ec-card-title"><h2>Templates</h2><span>{workflows.length}</span></div><div className="ec-table-wrap"><table className="ec-table"><thead><tr><th>Name</th><th>Document type</th><th>Reviewer rows</th><th>Status</th></tr></thead><tbody>{workflows.map(w=><tr key={w.id}><td>{w.name}</td><td>{w.docType}</td><td>{stageCount(w.steps)}</td><td><span className={`ec-badge ${w.active?'green':'amber'}`}>{w.active?'ACTIVE':'INACTIVE'}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
